name: Docker Frontend unit tests

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build dockerfile
      run: docker build -t vik98/docker-frontend -f Dockerfile.dev .
    - name: Run tests
      run: docker run -e CI=true vik98/docker-frontend npm test